import { Neighborhood, Post } from './types';

export const NEIGHBORHOODS: Neighborhood[] = [
  {
    id: 'n1',
    name: 'Fishtown',
    lat: 39.9755,
    lng: -75.1316,
    description: 'A vibrant neighborhood along the Delaware River.',
  },
  {
    id: 'n2',
    name: 'Kensington',
    lat: 39.9951,
    lng: -75.1246,
    description: 'A resilient community working toward revitalization.',
  },
  {
    id: 'n3',
    name: 'Northern Liberties',
    lat: 39.9629,
    lng: -75.1377,
    description: 'An eclectic neighborhood with strong community ties.',
  },
  {
    id: 'n4',
    name: 'Old City',
    lat: 39.9496,
    lng: -75.1457,
    description: 'Historic district at the heart of Philadelphia.',
  },
  {
    id: 'n5',
    name: 'Germantown',
    lat: 40.0343,
    lng: -75.1724,
    description: 'A diverse neighborhood with rich cultural heritage.',
  },
  {
    id: 'n6',
    name: 'University City',
    lat: 39.9522,
    lng: -75.1932,
    description: 'Home to UPenn and Drexel, with vibrant student and community life.',
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: 'c1',
    title: 'Free Water Refill Station',
    description: 'There is a free water refill station accessible right outside the community center. Great for hot days!',
    category: 'convenience',
    image_url: 'https://images.unsplash.com/photo-1549887552-cb1071d3e5ca?w=800&q=80',
    lat: 39.9740,
    lng: -75.1300,
    neighborhood_id: 'n1',
    neighborhood_name: 'Fishtown',
    author_name: 'Alex Rivera',
    author_avatar: 'https://i.pravatar.cc/150?img=3',
    upvotes: 42,
    status: 'resolved',
    created_at: '2026-04-10T12:00:00Z',
  },
  {
    id: 'c2',
    title: 'Accessible Public Restroom',
    description: 'Clean, accessible public restroom located near the park playground. Open dawn to dusk.',
    category: 'convenience',
    image_url: 'https://images.unsplash.com/photo-1541334658-1c4b724578ab?w=800&q=80',
    lat: 39.9955,
    lng: -75.1250,
    neighborhood_id: 'n2',
    neighborhood_name: 'Kensington',
    author_name: 'Marcus R.',
    author_avatar: 'https://i.pravatar.cc/150?img=52',
    upvotes: 112,
    status: 'resolved',
    created_at: '2026-04-09T08:00:00Z',
  },
  {
    id: 'p1',
    title: 'Vacant Lot on Trenton Ave Needs Cleanup',
    description:
      "This lot has been accumulating trash for months. It's right next to the elementary school — kids walk past it every day. Let's get this cleaned up and maybe turn it into a pocket park.",
    category: 'beautification',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    lat: 39.9762,
    lng: -75.1288,
    neighborhood_id: 'n1',
    neighborhood_name: 'Fishtown',
    author_name: 'Maria S.',
    author_avatar: 'https://i.pravatar.cc/150?img=47',
    upvotes: 142,
    status: 'acknowledged',
    created_at: '2026-04-08T10:23:00Z',
  },
  {
    id: 'p2',
    title: 'Crosswalk on Lehigh Ave Is Dangerous',
    description:
      'Cars regularly run this light. Two near-misses last week alone. We need a raised crosswalk or at minimum better signage and enforcement here.',
    category: 'safety',
    image_url: 'https://images.unsplash.com/photo-1515162305285-0293e4f3a1c3?w=800&q=80',
    lat: 39.9943,
    lng: -75.1255,
    neighborhood_id: 'n2',
    neighborhood_name: 'Kensington',
    author_name: 'James W.',
    author_avatar: 'https://i.pravatar.cc/150?img=12',
    upvotes: 218,
    status: 'open',
    created_at: '2026-04-07T14:11:00Z',
  },
  {
    id: 'p3',
    title: 'Street Lights Out on Girard Ave Block',
    description:
      "Four streetlights have been broken for two weeks between 2nd and 3rd St. It's pitch black at night and feels unsafe for everyone.",
    category: 'infrastructure',
    image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    lat: 39.9631,
    lng: -75.1369,
    neighborhood_id: 'n3',
    neighborhood_name: 'Northern Liberties',
    author_name: 'Priya K.',
    author_avatar: 'https://i.pravatar.cc/150?img=32',
    upvotes: 87,
    status: 'in_progress',
    created_at: '2026-04-09T09:45:00Z',
  },
  {
    id: 'p4',
    title: 'Community Mural for Norris Square',
    description:
      "The wall on N. American St. is a blank canvas. Let's commission a mural celebrating the neighborhood's Puerto Rican heritage. Artists are ready — we just need community support.",
    category: 'community',
    image_url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&q=80',
    lat: 39.9965,
    lng: -75.1221,
    neighborhood_id: 'n2',
    neighborhood_name: 'Kensington',
    author_name: 'Rosa M.',
    author_avatar: 'https://i.pravatar.cc/150?img=23',
    upvotes: 193,
    status: 'acknowledged',
    created_at: '2026-04-06T16:30:00Z',
  },
  {
    id: 'p5',
    title: 'Add Recycling Bins to Penn Treaty Park',
    description:
      "The park only has trash cans. People want to recycle but there's nowhere to put it. A few clearly labeled recycling stations would make a big difference.",
    category: 'environment',
    image_url: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&q=80',
    lat: 39.9748,
    lng: -75.1275,
    neighborhood_id: 'n1',
    neighborhood_name: 'Fishtown',
    author_name: 'Tom A.',
    author_avatar: 'https://i.pravatar.cc/150?img=60',
    upvotes: 64,
    status: 'open',
    created_at: '2026-04-10T11:20:00Z',
  },
  {
    id: 'p6',
    title: 'Potholes on Germantown Ave — Block 5500',
    description:
      'Multiple large potholes have been getting worse since winter. Two cars have had tire damage. Filed a 311 request months ago with no response.',
    category: 'infrastructure',
    image_url: 'https://images.unsplash.com/photo-1594804506344-7e96b0f13088?w=800&q=80',
    lat: 40.0341,
    lng: -75.1710,
    neighborhood_id: 'n5',
    neighborhood_name: 'Germantown',
    author_name: 'DeShawn B.',
    author_avatar: 'https://i.pravatar.cc/150?img=15',
    upvotes: 156,
    status: 'open',
    created_at: '2026-04-05T08:00:00Z',
  },
  {
    id: 'p7',
    title: 'More Seating Needed at Race Street Pier',
    description:
      "The pier is beautiful but there's almost nowhere to sit. Benches right now: 4 for the whole space. More seating would make it so much more welcoming.",
    category: 'community',
    image_url: 'https://images.unsplash.com/photo-1498550744921-75f79806b8a7?w=800&q=80',
    lat: 39.9501,
    lng: -75.1440,
    neighborhood_id: 'n4',
    neighborhood_name: 'Old City',
    author_name: 'Alice G.',
    author_avatar: 'https://i.pravatar.cc/150?img=41',
    upvotes: 103,
    status: 'open',
    created_at: '2026-04-10T15:00:00Z',
  },
  {
    id: 'p8',
    title: 'Stray Dogs Need a Safe House',
    description:
      "There's a pack of strays near the rail yard off Lehigh. They look malnourished. We need a rescue group or temp shelter here ASAP.",
    category: 'safety',
    image_url: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&q=80',
    lat: 39.9958,
    lng: -75.1230,
    neighborhood_id: 'n2',
    neighborhood_name: 'Kensington',
    author_name: 'Vanessa T.',
    author_avatar: 'https://i.pravatar.cc/150?img=26',
    upvotes: 79,
    status: 'open',
    created_at: '2026-04-11T07:30:00Z',
  },
  {
    id: 'p9',
    title: 'Plant Trees Along N. 2nd Street',
    description:
      "The stretch of 2nd from Girard to Susquehanna has zero tree cover. On hot days it's brutal to walk. Street trees would lower surface temps and look incredible.",
    category: 'environment',
    image_url: 'https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?w=800&q=80',
    lat: 39.9640,
    lng: -75.1358,
    neighborhood_id: 'n3',
    neighborhood_name: 'Northern Liberties',
    author_name: 'Claire D.',
    author_avatar: 'https://i.pravatar.cc/150?img=36',
    upvotes: 115,
    status: 'open',
    created_at: '2026-04-08T13:15:00Z',
  },
  {
    id: 'p10',
    title: 'Fix the Broken Playground at McPherson Square',
    description:
      'The swing set has been broken for 6 months. Three swings missing, one with a broken chain. Kids are still trying to use it. This needs to be fixed now.',
    category: 'safety',
    image_url: 'https://images.unsplash.com/photo-1575783970733-1aaedde1db74?w=800&q=80',
    lat: 39.9940,
    lng: -75.1270,
    neighborhood_id: 'n2',
    neighborhood_name: 'Kensington',
    author_name: 'Marcus R.',
    author_avatar: 'https://i.pravatar.cc/150?img=52',
    upvotes: 267,
    status: 'in_progress',
    created_at: '2026-04-04T09:00:00Z',
  },
  {
    id: 'p11',
    title: 'Community Garden Volunteer Days — UCity Grow',
    description:
      "UCity Grow is hosting open volunteer sessions every Saturday morning at the 43rd St community garden. Help plant, weed, and harvest — all are welcome. No experience needed, tools provided.",
    category: 'community',
    image_url: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800&q=80',
    lat: 39.9540,
    lng: -75.1950,
    neighborhood_id: 'n6',
    neighborhood_name: 'University City',
    author_name: 'Priya N.',
    author_avatar: 'https://i.pravatar.cc/150?img=44',
    upvotes: 88,
    status: 'open',
    created_at: '2026-04-09T08:00:00Z',
    is_anonymous: false,
    verified: true,
  },
  {
    id: 'p12',
    title: 'Free Tutoring at Lucien Blackwell Library',
    description:
      "UPenn student volunteers are offering free after-school tutoring (grades 3–8) at the Lucien Blackwell branch on Tuesdays and Thursdays 3–5 PM. Sign up on the library bulletin board.",
    category: 'community',
    image_url: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&q=80',
    lat: 39.9510,
    lng: -75.1910,
    neighborhood_id: 'n6',
    neighborhood_name: 'University City',
    author_name: 'Jordan L.',
    author_avatar: 'https://i.pravatar.cc/150?img=55',
    upvotes: 74,
    status: 'open',
    created_at: '2026-04-07T12:00:00Z',
    is_anonymous: false,
    verified: true,
  },
  {
    id: 'p13',
    title: 'Block Cleanup — Baltimore Ave Corridor',
    description:
      "Join neighbors for a Baltimore Ave corridor cleanup on April 19th, 9 AM–noon. Trash bags and gloves provided. Meet at the corner of 46th and Baltimore. Help us make our corridor shine.",
    category: 'beautification',
    image_url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&q=80',
    lat: 39.9499,
    lng: -75.2001,
    neighborhood_id: 'n6',
    neighborhood_name: 'University City',
    author_name: 'Samira O.',
    author_avatar: 'https://i.pravatar.cc/150?img=39',
    upvotes: 112,
    status: 'acknowledged',
    created_at: '2026-04-06T10:00:00Z',
    is_anonymous: false,
    verified: true,
  },
  {
    id: 'p14',
    title: 'Fix Broken Bike Lane on Spruce Street',
    description:
      "The protected bike lane on Spruce between 38th and 43rd has multiple missing bollards and a large crack near 40th St. Several cyclists have been forced into traffic. Needs urgent repair.",
    category: 'infrastructure',
    image_url: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800&q=80',
    lat: 39.9488,
    lng: -75.1960,
    neighborhood_id: 'n6',
    neighborhood_name: 'University City',
    author_name: 'Theo K.',
    author_avatar: 'https://i.pravatar.cc/150?img=17',
    upvotes: 145,
    status: 'open',
    created_at: '2026-04-10T09:30:00Z',
    is_anonymous: false,
    verified: true,
  },
  {
    id: 'p15',
    title: 'Community Seed Library at Clark Park',
    description:
      "The West Philly Seed Library is setting up a seed-sharing station at Clark Park this spring. Bring seeds to trade or take seeds for free. They're looking for volunteers to staff the table on weekends.",
    category: 'environment',
    image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80',
    lat: 39.9517,
    lng: -75.2043,
    neighborhood_id: 'n6',
    neighborhood_name: 'University City',
    author_name: 'Anika B.',
    author_avatar: 'https://i.pravatar.cc/150?img=29',
    upvotes: 93,
    status: 'open',
    created_at: '2026-04-08T14:00:00Z',
    is_anonymous: false,
    verified: true,
  },
];
